### ISSUE TITLE
Password length validation

### ISSUE THREAD

**Issue by rradz** [vic/comeonin_ecto_password#2]
Hello,
as far as I understand, password is changed to hash as soon as it is casted, which causes trouble with validation. Currently the only way is to use `Ecto.Changeset.change`, validate length and then do everything else (casting etc.). I believe there should be config option in this library to set up minimal password length, to make changesets look more standard. Alternatively, if there is simpler solution I'm missing, I believe it should be added to README.

**Comment by vic** [comment]
Hey sorry for the very late response.

This library is only intended to provide the ecto type to cast into a hashed password.

You are right, data is hashed as soon as you cast the params into the changeset (that's the purpose of cast and ecto types). So validation needs to be performed before casting. One way to do that would be to have a `field :clear_password, :string, virtual: true`on your schema, and use it for validation, or .. you can define a function like:

```elixir
def changeset(data, params) do
   data
   |> validate_password(params)
   |> cast(params, [:name, :email, :etc])
end

def validate_password(data, params) do
    {data, %{password: :string})
    |> cast(params, [:password])
    |> validate_length(:password, min: 6)
end
```

**Comment by hellomika** [comment]
Here's my take on it, if that helps:

```
def changeset(struct, params \\ %{}) do
  with %{valid?: true} <- validate_pin_code(struct, params) do
    struct
    |> cast(params, [:name_first, :name_middle, :name_last, :initials, :pin_code])
    |> validate_required([:name_first, :name_last, :initials, :pin_code])
  end
end

defp validate_pin_code(struct, params) do
  {struct, %{pin_code: :string}}
  |> cast(params, [:pin_code])
  |> validate_length(:pin_code, is: 4)
end
```

If the `pin_code` is valid, the full changeset is returned. If not, only the unvalidated `pin_code` changeset is returned which contains the reason why validation failed.

**Comment by vic** [comment]
Indeed @hellomika's code is much better than my not-tested example.

I'm closing this issue as we wont add validation code to this ecto type.

**Comment by jrgvf** [comment]
Hi, thanks @vic and @hellomika the answers helped me a lot, but I needed this error along with other errors.

This is my solution:

```
def insert_changeset(user, attrs) do
    user
    |> cast(attrs, @required_fields ++ @confirmation_fields)
    |> validate_required(@required_fields ++ @confirmation_fields)
    |> update_change(:email, &String.downcase/1)
    |> validate_format(:email, @email_regex)
    |> validate_confirmation(:email)
    |> validate_confirmation(:password)
    |> unique_constraint(:email)
    |> validate_password(user, attrs)
  end

def validate_password(changeset, user, attrs) do
    {user, %{password: :string}}
    |> cast(attrs, [:password])
    |> validate_length(:password, min: 8)
    |> merge(changeset) # https://github.com/elixir-ecto/ecto/blob/15e3f84f357811e300e8d8a1fdf9b25a7d5c352c/lib/ecto/changeset.ex#L905
  end
```

But this validation works only if it is the last one.
